version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acert
      POSTGRES_DB: acert
    container_name: postgres-db
    ports:
      - "5432:5432"



